services:
  mysql8:
    container_name: mysql8
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      #- ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      - payment-mysql:/var/lib/mysql
    restart: always
    networks:
      - payment-network

  payment:
    container_name: payment
    build: ./payment
    environment:
      - spring.datasource.url=jdbc:mysql://mysql8:3306/payment
      - kafka.bootstrap-servers=kafka:9092
      - service.customer:customer:8002/customer
    ports:
      - "8001:8001"
    networks:
      - payment-network
    depends_on:
      - mysql8
      - kafka
    restart: always

  customer:
    container_name: customer
    build: ./customer
    ports:
      - "8002:8002"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql8:3306/customer
      - kafka.bootstrap-servers=kafka:9092
    networks:
      - payment-network
    depends_on:
      - mysql8
      - kafka
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - payment-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - payment-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - payment-network
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

volumes:
  payment-mysql:

networks:
  payment-network:
    driver: bridge
    name: payment-network
